version: '2'

services:
  data-harness:
    restart: always
    privileged: true
    build:
      context: ./data-harness
      dockerfile: Dockerfile
    volumes_from:
      - data-vol
    ports:
      - "9001:80"
    environment:
      FOO: 'bar'
 data-vol:
    image: bitcalculus/lahmanpitcherdata:latest
